// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/ttx/dep"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/ttx/dep/db"
)

type TransactionDB struct {
	AddStatusListenerStub        func(string, chan db.TransactionStatusEvent)
	addStatusListenerMutex       sync.RWMutex
	addStatusListenerArgsForCall []struct {
		arg1 string
		arg2 chan db.TransactionStatusEvent
	}
	DeleteStatusListenerStub        func(string, chan db.TransactionStatusEvent)
	deleteStatusListenerMutex       sync.RWMutex
	deleteStatusListenerArgsForCall []struct {
		arg1 string
		arg2 chan db.TransactionStatusEvent
	}
	GetStatusStub        func(context.Context, string) (token.TxStatus, string, error)
	getStatusMutex       sync.RWMutex
	getStatusArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getStatusReturns struct {
		result1 token.TxStatus
		result2 string
		result3 error
	}
	getStatusReturnsOnCall map[int]struct {
		result1 token.TxStatus
		result2 string
		result3 error
	}
	GetStatusesStub        func(context.Context, []string) (map[string]db.TxStatusRecord, error)
	getStatusesMutex       sync.RWMutex
	getStatusesArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	getStatusesReturns struct {
		result1 map[string]db.TxStatusRecord
		result2 error
	}
	getStatusesReturnsOnCall map[int]struct {
		result1 map[string]db.TxStatusRecord
		result2 error
	}
	ListenerTxIDsStub        func() []string
	listenerTxIDsMutex       sync.RWMutex
	listenerTxIDsArgsForCall []struct {
	}
	listenerTxIDsReturns struct {
		result1 []string
	}
	listenerTxIDsReturnsOnCall map[int]struct {
		result1 []string
	}
	NotifyStub        func(db.TransactionStatusEvent)
	notifyMutex       sync.RWMutex
	notifyArgsForCall []struct {
		arg1 db.TransactionStatusEvent
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TransactionDB) AddStatusListener(arg1 string, arg2 chan db.TransactionStatusEvent) {
	fake.addStatusListenerMutex.Lock()
	fake.addStatusListenerArgsForCall = append(fake.addStatusListenerArgsForCall, struct {
		arg1 string
		arg2 chan db.TransactionStatusEvent
	}{arg1, arg2})
	stub := fake.AddStatusListenerStub
	fake.recordInvocation("AddStatusListener", []interface{}{arg1, arg2})
	fake.addStatusListenerMutex.Unlock()
	if stub != nil {
		fake.AddStatusListenerStub(arg1, arg2)
	}
}

func (fake *TransactionDB) AddStatusListenerCallCount() int {
	fake.addStatusListenerMutex.RLock()
	defer fake.addStatusListenerMutex.RUnlock()
	return len(fake.addStatusListenerArgsForCall)
}

func (fake *TransactionDB) AddStatusListenerCalls(stub func(string, chan db.TransactionStatusEvent)) {
	fake.addStatusListenerMutex.Lock()
	defer fake.addStatusListenerMutex.Unlock()
	fake.AddStatusListenerStub = stub
}

func (fake *TransactionDB) AddStatusListenerArgsForCall(i int) (string, chan db.TransactionStatusEvent) {
	fake.addStatusListenerMutex.RLock()
	defer fake.addStatusListenerMutex.RUnlock()
	argsForCall := fake.addStatusListenerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TransactionDB) DeleteStatusListener(arg1 string, arg2 chan db.TransactionStatusEvent) {
	fake.deleteStatusListenerMutex.Lock()
	fake.deleteStatusListenerArgsForCall = append(fake.deleteStatusListenerArgsForCall, struct {
		arg1 string
		arg2 chan db.TransactionStatusEvent
	}{arg1, arg2})
	stub := fake.DeleteStatusListenerStub
	fake.recordInvocation("DeleteStatusListener", []interface{}{arg1, arg2})
	fake.deleteStatusListenerMutex.Unlock()
	if stub != nil {
		fake.DeleteStatusListenerStub(arg1, arg2)
	}
}

func (fake *TransactionDB) DeleteStatusListenerCallCount() int {
	fake.deleteStatusListenerMutex.RLock()
	defer fake.deleteStatusListenerMutex.RUnlock()
	return len(fake.deleteStatusListenerArgsForCall)
}

func (fake *TransactionDB) DeleteStatusListenerCalls(stub func(string, chan db.TransactionStatusEvent)) {
	fake.deleteStatusListenerMutex.Lock()
	defer fake.deleteStatusListenerMutex.Unlock()
	fake.DeleteStatusListenerStub = stub
}

func (fake *TransactionDB) DeleteStatusListenerArgsForCall(i int) (string, chan db.TransactionStatusEvent) {
	fake.deleteStatusListenerMutex.RLock()
	defer fake.deleteStatusListenerMutex.RUnlock()
	argsForCall := fake.deleteStatusListenerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TransactionDB) GetStatus(arg1 context.Context, arg2 string) (token.TxStatus, string, error) {
	fake.getStatusMutex.Lock()
	ret, specificReturn := fake.getStatusReturnsOnCall[len(fake.getStatusArgsForCall)]
	fake.getStatusArgsForCall = append(fake.getStatusArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetStatusStub
	fakeReturns := fake.getStatusReturns
	fake.recordInvocation("GetStatus", []interface{}{arg1, arg2})
	fake.getStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *TransactionDB) GetStatusCallCount() int {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	return len(fake.getStatusArgsForCall)
}

func (fake *TransactionDB) GetStatusCalls(stub func(context.Context, string) (token.TxStatus, string, error)) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = stub
}

func (fake *TransactionDB) GetStatusArgsForCall(i int) (context.Context, string) {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	argsForCall := fake.getStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TransactionDB) GetStatusReturns(result1 token.TxStatus, result2 string, result3 error) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = nil
	fake.getStatusReturns = struct {
		result1 token.TxStatus
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *TransactionDB) GetStatusReturnsOnCall(i int, result1 token.TxStatus, result2 string, result3 error) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = nil
	if fake.getStatusReturnsOnCall == nil {
		fake.getStatusReturnsOnCall = make(map[int]struct {
			result1 token.TxStatus
			result2 string
			result3 error
		})
	}
	fake.getStatusReturnsOnCall[i] = struct {
		result1 token.TxStatus
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *TransactionDB) GetStatuses(arg1 context.Context, arg2 []string) (map[string]db.TxStatusRecord, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getStatusesMutex.Lock()
	ret, specificReturn := fake.getStatusesReturnsOnCall[len(fake.getStatusesArgsForCall)]
	fake.getStatusesArgsForCall = append(fake.getStatusesArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.GetStatusesStub
	fakeReturns := fake.getStatusesReturns
	fake.recordInvocation("GetStatuses", []interface{}{arg1, arg2Copy})
	fake.getStatusesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TransactionDB) GetStatusesCallCount() int {
	fake.getStatusesMutex.RLock()
	defer fake.getStatusesMutex.RUnlock()
	return len(fake.getStatusesArgsForCall)
}

func (fake *TransactionDB) GetStatusesCalls(stub func(context.Context, []string) (map[string]db.TxStatusRecord, error)) {
	fake.getStatusesMutex.Lock()
	defer fake.getStatusesMutex.Unlock()
	fake.GetStatusesStub = stub
}

func (fake *TransactionDB) GetStatusesArgsForCall(i int) (context.Context, []string) {
	fake.getStatusesMutex.RLock()
	defer fake.getStatusesMutex.RUnlock()
	argsForCall := fake.getStatusesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TransactionDB) GetStatusesReturns(result1 map[string]db.TxStatusRecord, result2 error) {
	fake.getStatusesMutex.Lock()
	defer fake.getStatusesMutex.Unlock()
	fake.GetStatusesStub = nil
	fake.getStatusesReturns = struct {
		result1 map[string]db.TxStatusRecord
		result2 error
	}{result1, result2}
}

func (fake *TransactionDB) GetStatusesReturnsOnCall(i int, result1 map[string]db.TxStatusRecord, result2 error) {
	fake.getStatusesMutex.Lock()
	defer fake.getStatusesMutex.Unlock()
	fake.GetStatusesStub = nil
	if fake.getStatusesReturnsOnCall == nil {
		fake.getStatusesReturnsOnCall = make(map[int]struct {
			result1 map[string]db.TxStatusRecord
			result2 error
		})
	}
	fake.getStatusesReturnsOnCall[i] = struct {
		result1 map[string]db.TxStatusRecord
		result2 error
	}{result1, result2}
}

func (fake *TransactionDB) ListenerTxIDs() []string {
	fake.listenerTxIDsMutex.Lock()
	ret, specificReturn := fake.listenerTxIDsReturnsOnCall[len(fake.listenerTxIDsArgsForCall)]
	fake.listenerTxIDsArgsForCall = append(fake.listenerTxIDsArgsForCall, struct {
	}{})
	stub := fake.ListenerTxIDsStub
	fakeReturns := fake.listenerTxIDsReturns
	fake.recordInvocation("ListenerTxIDs", []interface{}{})
	fake.listenerTxIDsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TransactionDB) ListenerTxIDsCallCount() int {
	fake.listenerTxIDsMutex.RLock()
	defer fake.listenerTxIDsMutex.RUnlock()
	return len(fake.listenerTxIDsArgsForCall)
}

func (fake *TransactionDB) ListenerTxIDsCalls(stub func() []string) {
	fake.listenerTxIDsMutex.Lock()
	defer fake.listenerTxIDsMutex.Unlock()
	fake.ListenerTxIDsStub = stub
}

func (fake *TransactionDB) ListenerTxIDsReturns(result1 []string) {
	fake.listenerTxIDsMutex.Lock()
	defer fake.listenerTxIDsMutex.Unlock()
	fake.ListenerTxIDsStub = nil
	fake.listenerTxIDsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *TransactionDB) ListenerTxIDsReturnsOnCall(i int, result1 []string) {
	fake.listenerTxIDsMutex.Lock()
	defer fake.listenerTxIDsMutex.Unlock()
	fake.ListenerTxIDsStub = nil
	if fake.listenerTxIDsReturnsOnCall == nil {
		fake.listenerTxIDsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.listenerTxIDsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *TransactionDB) Notify(arg1 db.TransactionStatusEvent) {
	fake.notifyMutex.Lock()
	fake.notifyArgsForCall = append(fake.notifyArgsForCall, struct {
		arg1 db.TransactionStatusEvent
	}{arg1})
	stub := fake.NotifyStub
	fake.recordInvocation("Notify", []interface{}{arg1})
	fake.notifyMutex.Unlock()
	if stub != nil {
		fake.NotifyStub(arg1)
	}
}

func (fake *TransactionDB) NotifyCallCount() int {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	return len(fake.notifyArgsForCall)
}

func (fake *TransactionDB) NotifyCalls(stub func(db.TransactionStatusEvent)) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = stub
}

func (fake *TransactionDB) NotifyArgsForCall(i int) db.TransactionStatusEvent {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	argsForCall := fake.notifyArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TransactionDB) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TransactionDB) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ dep.TransactionDB = new(TransactionDB)
